/////////////////////////
//production pipeline///
///////////////////////
pipeline {
    agent any

    environment {
        CHAT_TOKEN = credentials('google-chat-guisousa')
        GIT_URL = "https://github.com/gui-sousa/grafana-k8s.git"
        GIT_BRANCH = "master"
        K8s_TOKEN = "k3s-croacia"
        APP_URL = "http://10.1.80.81:32004/"
        NAMESPACE = "dev"
    }

    stages {
        stage('Update Code') {
            steps {
                git branch: "$GIT_BRANCH", url: "$GIT_URL"
            }

            post {
                always {
                   hangoutsNotify message: "⚙️ Iniciando build\n⏰ Horario de início: $BUILD_TIMESTAMP", token: "$CHAT_TOKEN", threadByJob: false
                }
            }
        }

        stage('Deploy Kubernetes') {
            steps {
                withKubeConfig([credentialsId: "&K8s_TOKEN"]) {
                    sh 'curl -LO "https://storage.googleapis.com/kubernetes-release/release/v1.20.5/bin/linux/amd64/kubectl"'
                    sh 'chmod +x kubectl'
                    sh 'sed -i "s|\\$NAMESPACE|$NAMESPACE|g" service.yaml'
                    sh 'sed -i "s|\\$NAMESPACE|$NAMESPACE|g" deployment.yaml' 
                    sh './kubectl apply -f service.yaml'
                    sh './kubectl apply -f deployment.yaml'
                }
            }
        }

        stage('Test Grafana login Page') {
            steps {
                httpRequest consoleLogResponseBody: true, responseHandle: 'NONE', url: "$APP_URL", validResponseCodes: '200', validResponseContent: 'Grafana'
            }
        }
    }

    post {
        success {
            hangoutsNotify message: "✅ Deu Certo!\n⏰ Tempo de Duração: ${currentBuild.duration / 1000} segundos", token: "$CHAT_TOKEN", threadByJob: false
        }

        failure {
           hangoutsNotify message: "❌ Deu Errado!\n⏰ Tempo de Duração: ${currentBuild.duration / 1000} segundos", token: "$CHAT_TOKEN", threadByJob: false 
        }
    } 
}
