apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-bwg
  namespace: $(NAMESPACE-DEV)
spec:
  selector:
    matchLabels:
      app: grafana-bwg
  template:
    metadata:
      labels:
        app: grafana-bwg
    spec:
      containers:
      - name: myapp
        image: guisousa/grafana-bwg:latest
        resources:
#          limits:
#           //Ainda a definir//
#            memory: "128Mi"
#            cpu: "500m"
        ports:
        - name: grafana-port
          containerPort: 3000
