apiVersion: v1
kind: Service
metadata:
  name: grafana-bwg
  namespace: default
spec:
  selector:
    app: grafana-bwg
  ports:
  - name: grafana-bwg-port
    port: 3000
    targetPort: 3000
