apiVersion: v1
kind: Service
metadata:
  name: grafana-bwg
  namespace: env-namespace
  valueFrom:
    configMapKeyRef:
      name: namespace
      key: env-namespace
spec:
  type: NodePort
  selector:
    app: grafana-bwg
  ports:
  - name: grafana-port
    port: 3000
    targetPort: 3000
    nodePort: 32004
