{
 "title": "Servidores BWG - Produção",
 "description": "Métricas de processamento e status da instancia",
 "tags": [
  "bwg",
  "prod",
  "oci"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "INSTÂNCIA",
    "query": "label_values(windows_system_system_up_time, job)"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "description": "A consulta calcula o tempo de atividade do sistema Windows, excluindo o tempo em que o processo Idle estava ativo.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "windows_os_time{job=\"$job\"} - on () windows_process_start_time{creating_process_id=\"0\", job=\"$job\",process=\"Idle\",process_id=\"0\"}"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(windows_cpu_time_total{mode=\"idle\", job=\"$job\"}[1m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(windows_cpu_time_total{mode=\"idle\", job=\"$job\"}[1m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(100 - ((windows_os_physical_memory_free_bytes{job=\"$job\"} * 100) / windows_os_visible_memory_bytes{job=\"$job\"})) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(irate(windows_net_bytes_total{job=\"$job\"}[1m])) > 1)* 8"
    }
   ]
  },
  {
   "title": "Uso do Disco Rígido + Volume ",
   "type": "bargauge",
   "description": "A consulta calcula a porcentagem de espaço em disco utilizado em um sistema Windows.",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (windows_logical_disk_free_bytes{job=\"$job\"} / windows_logical_disk_size_bytes{job=\"$job\"})*100",
     "legendFormat": "{{volume}}"
    }
   ]
  },
  {
   "title": "Sessões Ativas",
   "type": "stat",
   "description": "A consulta retorna o número de usuários que fizeram login no sistema Windows por meio de uma rede.\nA métrica não é confiável e pode retornar resultados inconsistentes.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "windows_logon_logon_type{job=\"$job\", status=\"network\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "description": "A consulta calcula o percentual de uso da CPU por cada processo em um sistema Windows, excluindo o processo Idle (ocioso).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (sum(rate(windows_process_cpu_time_total{job=\"$job\", process!=\"Idle\"}[$__rate_interval])) by (process) / on(job) group_left sum(rate(windows_process_cpu_time_total{job=\"$job\"}[$__rate_interval])))\r\n\r\n\r\n#100 * sum(rate(windows_process_cpu_time_total{job=\"$job\", instance=\"$instance\", process!=\"Idle\"}[$__rate_interval])) by (process)\r\n\r\n#sum by (process) (irate(windows_process_cpu_time_total{job=\"$job\", instance=\"$instance\", process!=\"Idle\"}[5m])) / sum(irate(windows_process_cpu_time_total{job=\"$job\", instance=\"$instance\", process!=\"Idle\"}[5m])) * 100 ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memória",
   "type": "timeseries",
   "description": "A consulta calcula o uso de memória virtual por cada processo em um sistema Windows",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "\r\nsum by (process) (windows_process_working_set_bytes{job=\"$job\"})\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(windows_cpu_time_total{mode=\"idle\", job=\"$job\"}[1m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(100 - ((windows_os_physical_memory_free_bytes{job=\"$job\"} * 100) / windows_os_visible_memory_bytes{job=\"$job\"})) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Escritas por Processo",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "irate(windows_process_io_bytes_total{mode=\"write\", job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{process}} ({{process_id}})"
    }
   ]
  },
  {
   "title": "Leituras por Processo",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "irate(windows_process_io_bytes_total{mode=\"read\", job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{process}} ({{process_id}})"
    }
   ]
  }
 ]
}